### ISSUE TITLE
Multimedia tests of GTS are failing on Nitrogen6x running Android 7.1.1

### ISSUE THREAD

**Issue by saiyamd** [boundarydevices/frameworks_av#1]
What I have observed is,

When I execute "GtsMediaTestCases -com.google.android.media.gts.WidevineDashPolicyTests#testL30SLicense20SPlayback" (there are few more tests similar to this).

In background, it downloads below video and detects the video with mime-type "video/avc"
https://storage.googleapis.com/wvmedia/cenc/h264/llama/llama_h264_main_480p_2000.mp4
https://storage.googleapis.com/wvmedia/cenc/h264/llama/llama_aac_audio.mp4

Here, for video it selects "OMX.Freescale.std.video_decoder.avc.v3.hw-based". If I disable - "OMX.Freescale.std.video_decoder.avc.v3.hw-based" from "media_codecs_vpu.xml" it selects Google's OMX.google.h264.decoder.

for Audio it selects "OMX.google.aac.decoder" for mime type "audio/mp4a-latm"

In both the cases, after few seconds of video playback (max 5 sec.) the video freezes and green overlays visible on the screen. And audio stops playing with below error.

02-13 03:27:26.442  5467  5503 V ACodec  : [OMX.google.aac.decoder] calling emptyBuffer 4 w/ time 20015600 us
02-13 03:27:26.442   233  5504 W SoftAAC2: aacDecoder_DecodeFrame decoderErr = 0x4004
02-13 03:27:26.442   233  5504 W SoftAAC2: AAC decoder returned error 0x4004, substituting silence
02-13 03:27:26.443  5467  5503 V ACodec  : [OMX.google.aac.decoder] onOMXEmptyBufferDone 4
02-13 03:27:26.443  5467  5503 V ACodec  : [OMX.google.aac.decoder] onOMXFillBufferDone 15 time 14558911 us, flags = 0x00000000
02-13 03:27:26.443  5467  5503 V ACodec  : [OMX.google.aac.decoder] calling fillBuffer 16
02-13 03:27:26.444   235   256 V FslExtractor: GetNextSample readmode=1 index=0 BEGIN
02-13 03:27:26.444   235   256 V FslExtractor: appRequestBuffer streamNum=0
02-13 03:27:26.444   235   256 V FslExtractor: GetNextSample err 0 get track num=0 ts=20038820,size=384,flag=1
02-13 03:27:26.444   235   256 V FslExtractor: addMediaBuffer ts=20038820,size=384
02-13 03:27:26.444   235   256 V FslExtractor: FslMediaSource::read mSourceIndex=0 size=384,time 0
02-13 03:27:26.446  5467  5503 V ACodec  : [OMX.google.aac.decoder] calling emptyBuffer 1 w/ time 20038820 us

Logs and sample image attached. Can you please look into the issue and suggest a fix for this?

Thanks,
saiyam

[gts.logcat.google.h264.decoder.log](https://github.com/boundarydevices/frameworks_av/files/1718581/gts.logcat.google.h264.decoder.log)

![dec96b7b-8a04-42b6-893e-2ed8a5c04d50](https://user-images.githubusercontent.com/15319265/36132615-53344658-109e-11e8-9e84-6cb50649ea47.jpg)

**Comment by saiyamd** [comment]
Issue tracked down to usage of "FslExtractor" instead of default media extractor in "media/libstagefright/MediaExtractor.cpp" file.

Below is the patch in which fsl extractor for media was added.

> 9f89507d221d243b281a3952e1eaecf16792d9f0
> MA-7590: Add fsl extractor in stagefright player.

Right now by specifying - "use_fsl = false;", it is able to parse media streams properly and the above-mentioned test is getting passed. I am able to observe the proper AV stream without any artifact. 

Just for my understanding, if you know, is there any dependency of using fsl extractor instead of default one due to fsl specific hw/sw codecs?

**Comment by gibsson** [comment]
Hi,

As you can see in the source code, Boundary Devices has made no changes to audio/video codec handling in Android. So we recommend asking those question to NXP directly:
https://community.nxp.com/community/imx/content

As for the difference of extractor, I guess the main value-add of the FSL one is that it supports more formats but my guess is that it doesn't change the decoding process.

Regards

**Comment by nabilt** [comment]
@saiyamd, Did you find a final resolution for this or are you using the workaround still? I'm seeing this while playing Youtube videos in a webview.
